services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
    env_file:
        - .env
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped
